site_name: Nikunj Bhalotia — MSc Cyber Security e-Portfolio
site_url: https://nikunjb.com
repo_url: https://github.com/nb25877/nb25877.github.io
site_description: Academic e-portfolio for the MSc in Cyber Security (University of Essex Online)
use_directory_urls: true

theme:
  name: material
  language: en
  logo: assets/images/profile.png
  favicon: assets/favicon-shield.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - toc.follow
    - search.suggest
    - search.highlight
    - header.autohide
    - announce.dismiss
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nbhal/
      name: LinkedIn
  generator: false
  analytics:  # add later if you want (e.g., plausible or GA4)
    provider: false
  status:
    new: Recently added
    updated: Updated

plugins:
  - search
  - tags
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: false
      type: date
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - About Me: index.md
  - Modules:
      - modules/index.md
      - Introduction to Computing: modules/introduction-to-computing.md
      # Duplicate the template below for new modules:
  - Certifications: certifications.md
  - Contact: contact.md